spring:
  mustache:
    expose-request-attributes: true

# Main menu items
webui.menus:
  menuLayout:
    - nameProperty: users.label
      menuItems:
        - nameProperty: logIn.label
          path: /login
        - nameProperty: logOut.label
          path: /logout
          validUserRoles:
            - ROLE_USER
            - ROLE_ADMIN
        - nameProperty: userDetails.label
          path: /userinfo
          validUserRoles:
            - ROLE_USER
            - ROLE_ADMIN
        - nameProperty: newUser.label
          path: /newuser
          validUserRoles:
            - ROLE_ADMIN
    - nameProperty: data.menu.label
      menuItems:
        - nameProperty: propertyList.label
          path: /property
          validUserRoles:
            - ROLE_USER
            - ROLE_ADMIN
        - nameProperty: roomList.label
          path: /room
          validUserRoles:
            - ROLE_USER
            - ROLE_ADMIN