spring:
  profiles: test_h2
  h2.console.enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:homeinventory;DB_CLOSE_ON_EXIT=FALSE
    username: homeinventory
    password: insecurepassword
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
    hibernate.ddl-auto: none
  data.mongodb:
    host: localhost
    port: 27017
    database: homeinventory