spring.datasource:
  url: jdbc:mariadb://localhost/homeinventory
  username: homeinventory
  password: insecurepassword
server:
  port: 8778
spring.data.mongodb:
  host: localhost
  port: 27017
  database: homeinventory
spring.servlet.multipart:
  max-file-size: 256MB
  max-request-size: 256MB
  enabled: true
spring.jpa:
  show-sql: true
  properties.hibernate.format_sql: true

security.rememberme.key: mdnumBcFXfwCxTIF16qo

jasper.reporting:
  groupByRoomCategoryReportPath: ./config/reports/Home_Inventory_room_category.jrxml
  groupByPropertyCategoryReportPath: ./config/reports/Home_Inventory_property_category.jrxml
  groupByPropertyRoomReportPath: ./config/reports/Home_Inventory_property_room.jrxml
  groupByRoomReportPath: ./config/reports/Home_Inventory_room.jrxml
  groupByCategoryReportPath: ./config/reports/Home_Inventory_category.jrxml


