spring:
  profiles: neo4j
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: insecurepassword
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true

attachment-document-repository:
  type: neo4j