spring:
  profiles: test_mariadb
  datasource:
    url: jdbc:mariadb://localhost/homeinventory
    username: root
    password:
  data.mongodb:
    host: localhost
    port: 27017
    database: homeinventory
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true