server:
  port: 8778

spring:
  servlet.multipart:
    max-file-size: 100MB
    max-request-size: 100MB
    enabled: true

logging:
  level:
    root: DEBUG
    com.irotsoma: DEBUG
    org.springframework: DEBUG
  file:
    path: ./logs

security.rememberme.key: mdnumBcFXfwCxTIF16qo

reporting.jasper:
  group-by-room-category-report-path: ./config/reports/Home_Inventory_room_category.jrxml
  group-by-property-category-report-path: ./config/reports/Home_Inventory_property_category.jrxml
  group-by-property-room-report-path: ./config/reports/Home_Inventory_property_room.jrxml
  group-by-room-report-path: ./config/reports/Home_Inventory_room.jrxml
  group-by-category-report-path: ./config/reports/Home_Inventory_category.jrxml

attachment-document-repository:
  type: mongodb

