server:
  port: 8778
spring:
  datasource:
    url: jdbc:mariadb://localhost/homeinventory
    username: homeinventory
    password: insecurepassword
  data.mongodb:
    authentication-database: admin
    host: localhost
    port: 27017
    database: homeinventory
  servlet.multipart:
    max-file-size: 100MB
    max-request-size: 100MB
    enabled: true
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
  messages.basename: messages

security.rememberme.key: mdnumBcFXfwCxTIF16qo

jasper.reporting:
  groupByRoomCategoryReportPath: ./config/reports/Home_Inventory_room_category.jrxml
  groupByPropertyCategoryReportPath: ./config/reports/Home_Inventory_property_category.jrxml
  groupByPropertyRoomReportPath: ./config/reports/Home_Inventory_property_room.jrxml
  groupByRoomReportPath: ./config/reports/Home_Inventory_room.jrxml
  groupByCategoryReportPath: ./config/reports/Home_Inventory_category.jrxml

